name = "cf-ai-queue-assistant"
main = "src/index.ts"
compatibility_date = "2026-01-01"

[assets]
directory = "./public"
binding = "ASSETS"

[ai]
binding = "AI"
remote = true

[durable_objects]
bindings = [
  { name = "QUEUE", class_name = "QueueDO" }
]

[[migrations]]
tag = "v1"
new_classes = ["QueueDO"]